name: CD Pipeline for Angular Frontend

on:
  push:
    branches:
      - staging
      - production

jobs:

  build-and-push:
    name: ğŸ› ï¸ Build & Push Docker image
    runs-on: ubuntu-latest

    outputs:
      tag: ${{ steps.set_tag.outputs.tag }}
      dockerfile: ${{ steps.set_tag.outputs.dockerfile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set Docker image tag and Dockerfile
        id: set_tag
        run: |
          if [[ "${GITHUB_REF##*/}" == "production" ]]; then
            echo "tag=production" >> "$GITHUB_OUTPUT"
            echo "dockerfile=docker/Dockerfile.production" >> "$GITHUB_OUTPUT"
          else
            echo "tag=staging" >> "$GITHUB_OUTPUT"
            echo "dockerfile=docker/Dockerfile.staging" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.set_tag.outputs.dockerfile }}
          push: true
          tags: sarakadimi/angular-app:${{ steps.set_tag.outputs.tag }}

  deploy:
    name: ğŸš€ Deploy to VPS
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_PRIVATE_KEY }}" > ~/.ssh/id_ed25519_frontend
          chmod 600 ~/.ssh/id_ed25519_frontend

      - name: SSH to VPS and deploy
        run: |
          TAG=${{ needs.build-and-push.outputs.tag }}
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519_frontend ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
            cd /home/${{ secrets.VPS_USER }}/frontend/$TAG
            docker compose pull
            docker compose down && docker compose up -d
          EOF

  health-check:
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      - name: VÃ©rifier le health endpoint
        id: health
        run: |
          URL_FRONT=https://utilix.fr/health
          if [[ "${GITHUB_REF##*/}" == "staging" ]]; then
            URL_FRONT=https://staging.utilix.fr/health
          fi
          RESPONSE=$(curl -s $URL_FRONT || echo "error")
          echo "RÃ©ponse du serveur : $RESPONSE"

          if [ "$RESPONSE" = '{"status":"OK"}' ]; then
            echo "status=ok" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi

      - name: Envoyer email (succÃ¨s)
        if: steps.health.outputs.status == 'ok'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.mail.ovh.net
          server_port: 465
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "âœ… DÃ©ploiement rÃ©ussi"
          to: ${{ secrets.MAIL_TO }}
          from: "CI-CD Bot <${{ secrets.SMTP_USER }}>"
          body: |
            âœ”ï¸ Le dÃ©ploiement de la version ${{ needs.build-and-push.outputs.tag }} a rÃ©ussi ğŸ‰
            âœ… Health check OK : l'application est en ligne !

      - name: Envoyer email (Ã©chec)
        if: steps.health.outputs.status == 'fail'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}
          subject: "âŒ DÃ©ploiement Ã©chouÃ©"
          to: ${{ secrets.MAIL_TO }}
          from: "CI-CD Bot <${{ secrets.SMTP_USER }}>"
          body: |
            â— Le dÃ©ploiement de la version ${{ needs.build-and-push.outputs.tag }} a Ã©chouÃ© âŒ
            ğŸš« Health check KO : http://serveur.fr/health n'a pas renvoyÃ© {"status":"OK"}.
            âš ï¸ Merci de vÃ©rifier les logs et l'application.
